Repository GafferHQ/gaffer, pull requests merged in 2018-03, with the labels that each got.

#2473 Highlight AuxiliaryConnections if connected NodeGadgets are highlighted
  include/GafferUI/StandardConnectionGadget.h
  include/GafferUI/StandardStyle.h
  include/GafferUI/Style.h
  src/GafferUI/AuxiliaryConnectionsGadget.cpp
  src/GafferUI/StandardConnectionGadget.cpp
  src/GafferUI/StandardStyle.cpp
Labels: pr-majorVersion

#2452 Rename IECoreScene::Display to IECoreScene::Output
  config/travis/installDependencies.sh
  include/GafferScene/Outputs.h
  include/GafferScene/Private/IECoreScenePreview/Renderer.h
  include/GafferScene/RendererAlgo.h
  python/GafferAppleseedTest/AppleseedRenderTest.py
  python/GafferArnoldTest/ArnoldRenderTest.py
  python/GafferArnoldTest/ArnoldShaderTest.py
  python/GafferArnoldTest/IECoreArnoldPreviewTest/RendererTest.py
  python/GafferArnoldTest/InteractiveArnoldRenderTest.py
  python/GafferDelightTest/IECoreDelightPreviewTest/RendererTest.py
  python/GafferSceneTest/DeleteOutputsTest.py
  python/GafferSceneTest/IECoreGLPreviewTest/RendererTest.py
  python/GafferSceneTest/InstancerTest.py
  python/GafferSceneTest/InteractiveRenderTest.py
  python/GafferSceneTest/OpenGLRenderTest.py
  python/GafferSceneTest/OutputsTest.py
  python/GafferSceneUI/OutputsUI.py
  src/GafferArnold/IECoreArnoldPreview/Renderer.cpp
  src/GafferDelight/IECoreDelightPreview/Renderer.cpp
  src/GafferScene/IECoreGLPreview/Renderer.cpp
  src/GafferScene/Outputs.cpp
  src/GafferScene/Render.cpp
  src/GafferScene/RendererAlgo.cpp
  src/GafferSceneModule/GlobalsBinding.cpp
  src/GafferSceneUI/ShaderView.cpp
  startup/gui/outputs.py
Labels: pr-externalDependency, pr-majorVersion

#2462 Startup improvements
  python/Gaffer/__init__.py
  python/GafferAppleseed/__init__.py
  python/GafferAppleseedUI/__init__.py
  python/GafferArnold/__init__.py
  python/GafferArnoldUI/__init__.py
  python/GafferCortex/__init__.py
  python/GafferCortexUI/__init__.py
  python/GafferDelight/__init__.py
  python/GafferDelightUI/__init__.py
  python/GafferDispatch/__init__.py
  python/GafferDispatchUI/__init__.py
  python/GafferImage/__init__.py
  python/GafferImageUI/__init__.py
  python/GafferOSL/__init__.py
  python/GafferOSLUI/__init__.py
  python/GafferScene/__init__.py
  python/GafferSceneUI/__init__.py
  python/GafferTractor/__init__.py
  python/GafferTractorUI/__init__.py
  python/GafferUI/__init__.py
  python/GafferVDB/__init__.py
  python/GafferVDBUI/__init__.py
  startup/Gaffer/compoundPlugCompatibility.py
  startup/Gaffer/undoContextCompatibility.py
  startup/Gaffer/userPlugCompatibility.py
  startup/GafferScene/arnoldLights.py
  startup/GafferScene/delightLights.py
Labels: pr-externalDependency

#2486 Selection/Expansion improvement followup
  include/GafferSceneUI/ContextAlgo.h
  include/GafferSceneUI/SceneGadget.h
  python/GafferSceneUI/SceneHierarchy.py
  python/GafferSceneUI/SceneInspector.py
  python/GafferSceneUITest/ContextAlgoTest.py
  python/GafferSceneUITest/SceneGadgetTest.py
  python/GafferSceneUITest/SceneHierarchyTest.py
  src/GafferSceneUI/ContextAlgo.cpp
  src/GafferSceneUI/SceneGadget.cpp
  src/GafferSceneUI/SceneView.cpp
  src/GafferSceneUI/SelectionTool.cpp
  src/GafferSceneUI/TransformTool.cpp
  src/GafferSceneUIModule/ContextAlgoBinding.cpp
  src/GafferSceneUIModule/GafferSceneUIModule.cpp
Labels: pr-majorVersion

#2479 GLWidget : Support Qt5 builds of Houdini
  python/GafferUI/GLWidget.py
Labels: pr-backport

#2478 PlugAdder : Fix crash when dragging from a plug without a nodule.
  src/GafferUI/PlugAdder.cpp
Labels: pr-backport

#2493 Backports
  python/Gaffer/PythonExpressionEngine.py
  python/GafferTest/ExpressionTest.py
  python/GafferUI/Backups.py
  python/GafferUI/ExpressionUI.py
  python/GafferUI/FileMenu.py
  python/GafferUI/SplinePlugValueWidget.py
  python/GafferUI/__init__.py
  python/GafferUITest/BackupsTest.py
  python/GafferUITest/__init__.py
  startup/gui/menus.py
Labels: pr-backport

#2491 Layout improvements (backport)
  python/GafferUI/LayoutMenu.py
  python/GafferUI/Layouts.py
Labels: pr-backport

#2498 Backups : Fix preferences UI
  python/GafferUI/Backups.py
Labels: pr-backport

#2506 Safe backports
  .travis.yml
  include/Gaffer/ScriptNode.h
  python/GafferTest/ScriptNodeTest.py
  python/GafferUI/Backups.py
  python/GafferUI/CompoundEditor.py
  python/GafferUI/PlugValueWidget.py
  python/GafferUI/ScriptNodeUI.py
  python/GafferUI/ScriptWindow.py
  src/Gaffer/ScriptNode.cpp
Labels: pr-backport

#2501 GafferArnold : Support multiple outputs on OSL shaders ( backport )
  python/GafferArnoldTest/ArnoldVDBTest.py
  python/GafferArnoldTest/IECoreArnoldPreviewTest/RendererTest.py
  src/GafferArnold/IECoreArnoldPreview/Renderer.cpp
  src/GafferArnold/IECoreArnoldPreview/ShaderAlgo.cpp
Labels: pr-backport

#2510 Viewer camera backport
  doc/source/Reference/UIReference/Viewer.md
  include/GafferUI/ImageGadget.h
  include/GafferUI/View.h
  include/GafferUI/ViewportGadget.h
  python/GafferSceneUI/SceneViewUI.py
  python/GafferSceneUITest/SceneViewTest.py
  python/GafferUI/Viewer.py
  python/GafferUI/Widget.py
  resources/graphics.svg
  src/GafferImageUI/ImageView.cpp
  src/GafferSceneUI/SceneView.cpp
  src/GafferSceneUIModule/GafferSceneUIModule.cpp
  src/GafferUI/ImageGadget.cpp
  src/GafferUI/View.cpp
  src/GafferUI/ViewportGadget.cpp
  src/GafferUIBindings/ViewportGadgetBinding.cpp
Labels: pr-backport
