Repository GafferHQ/gaffer, pull requests merged in 2018-10, with the labels that each got.

#2832 Docs : Add "Anatomy of an Image"
  doc/source/WorkingWithImages/AnatomyOfAnImage/images/gafferImageCoordinates.png
  doc/source/WorkingWithImages/AnatomyOfAnImage/images/gafferImageCoordinates.svg
  doc/source/WorkingWithImages/AnatomyOfAnImage/images/gafferImageWindows.png
  doc/source/WorkingWithImages/AnatomyOfAnImage/images/gafferImageWindows.svg
  doc/source/WorkingWithImages/AnatomyOfAnImage/index.md
  doc/source/WorkingWithImages/index.md
  doc/source/index.md
Labels: component-docs

#2858 Backports for 0.51
  Changes
  SConstruct
  doc/source/index.md
  python/GafferImageTest/ImageMetadataTest.py
  python/GafferSceneTest/FilterProcessorTest.py
  python/GafferSceneTest/ShaderAssignmentTest.py
  python/GafferSceneTest/UnionFilterTest.py
  python/GafferSceneTest/__init__.py
  python/GafferSceneTest/scripts/filterProcessor-0.27.0.0.gfr
  src/GafferImage/ImageNode.cpp
  src/GafferScene/IECoreGLPreview/Renderer.cpp
  src/GafferScene/SceneElementProcessor.cpp
  startup/GafferScene/switchCompatibility.py
Labels: pr-backport

#2867 Backports from master to 0.51_maintenance
  Changes
  SConstruct
  python/GafferCortexUI/ParameterisedHolderUI.py
  python/GafferImageTest/ImageSwitchTest.py
  python/GafferSceneTest/FilterProcessorTest.py
  python/GafferSceneTest/SceneReaderTest.py
  python/GafferSceneTest/SceneSwitchTest.py
  python/GafferSceneTest/SceneWriterTest.py
  python/GafferSceneTest/scripts/filterProcessorBoxed-0.27.0.0.gfr
  python/GafferSceneUI/PrimitiveInspector.py
  python/GafferSceneUI/SceneInspector.py
  python/GafferSceneUI/__init__.py
  python/GafferTest/SwitchTest.py
  python/GafferUI/AboutWindow.py
  python/GafferUI/Enums.py
  python/GafferUI/PlugLayout.py
  python/GafferUI/ScrolledContainer.py
  python/GafferUI/UIEditor.py
  python/GafferUI/VectorDataWidget.py
  python/GafferUI/_StyleSheet.py
  src/Gaffer/Switch.cpp
  src/GafferScene/SceneWriter.cpp
  startup/GafferScene/switchCompatibility.py
  startup/gui/layouts.py
Labels: pr-backport

#2868 Wrapper : Support 3rd party extensions.
  bin/gaffer
Labels: docs-addNew

#2870 Backports for 0.52_maintenance
  Changes
  SConstruct
  bin/gaffer
  python/GafferCortexUI/ParameterisedHolderUI.py
  python/GafferSceneTest/FilterProcessorTest.py
  python/GafferSceneTest/SceneReaderTest.py
  python/GafferSceneTest/SceneWriterTest.py
  python/GafferSceneTest/scripts/filterProcessorBoxed-0.27.0.0.gfr
  python/GafferSceneUI/PrimitiveInspector.py
  python/GafferSceneUI/SceneInspector.py
  python/GafferSceneUI/__init__.py
  python/GafferUI/AboutWindow.py
  python/GafferUI/Enums.py
  python/GafferUI/PlugLayout.py
  python/GafferUI/ScrolledContainer.py
  python/GafferUI/UIEditor.py
  python/GafferUI/VectorDataWidget.py
  python/GafferUI/_StyleSheet.py
  src/GafferScene/SceneWriter.cpp
  startup/GafferScene/switchCompatibility.py
  startup/GafferScene/usd.py
  startup/gui/layouts.py
Labels: pr-backport

#2593 SConstruct : DEBUGINFO build option to generate debug info in release.
  .travis.yml
  SConstruct
Labels: pr-revisionRequired

#2873 Bookmark search
  python/GafferSceneUI/SceneInspector.py
  python/GafferTest/MetadataAlgoTest.py
  python/GafferTest/scripts/legacyBookmarks.gfr
  python/GafferUI/CompoundEditor.py
  python/GafferUI/Editor.py
  python/GafferUI/GraphBookmarksUI.py
  python/GafferUI/Menu.py
  python/GafferUI/NodeEditor.py
  src/Gaffer/MetadataAlgo.cpp
  startup/Gaffer/metadataCompatibility.py
  startup/gui/editor.py
Labels: docs-addNew
