Repository GafferHQ/gaffer, pull requests merged in 2018-05, with the labels that each got.

#2562 Build : Update IE config for more modern OIIO and OSL
  config/ie/options
Labels: pr-onHold

#2536 Metadata matching improvements
  python/GafferCortexUI/FileSequenceParameterValueWidget.py
  python/GafferCortexUI/ObjectWriterUI.py
  python/GafferCortexUI/ParameterisedHolderUI.py
  python/GafferCortexUI/StringParameterValueWidget.py
  python/GafferDispatchUI/TaskNodeUI.py
  python/GafferSceneUI/OutputsUI.py
  python/GafferTest/MetadataTest.py
  python/GafferUI/BoxUI.py
  python/GafferUI/NodeUI.py
  python/GafferUI/PlugValueWidget.py
  python/GafferUITest/StandardNodeGadgetTest.py
  src/Gaffer/Metadata.cpp
  startup/gui/nodeGraph.py
Labels: pr-majorVersion

#2522 Layout Improvements
  python/GafferUI/CompoundEditor.py
  python/GafferUI/SplitContainer.py
  startup/gui/layouts.py
Labels: pr-majorVersion

#2561 ImageAlgo refactoring
  include/GafferImage/ImageAlgo.h
  include/GafferImage/ImageAlgo.inl
  python/GafferImageTest/ImageAlgoTest.py
  src/GafferImage/Catalogue.cpp
  src/GafferImage/ImagePlug.cpp
  src/GafferImage/ImageWriter.cpp
  src/GafferImageModule/ImageAlgoBinding.cpp
Labels: pr-majorVersion

#2563 TBBTaskScheduler has moved to Cortex
  python/Gaffer/Application.py
  python/GafferTest/ApplicationTest.py
  src/GafferModule/GafferModule.cpp
Labels: pr-externalDependency

#2574 Dispatcher : Add `dispatchSignal()`
  include/GafferDispatch/Dispatcher.h
  python/GafferDispatchTest/DispatcherTest.py
  python/GafferDispatchTest/LocalDispatcherTest.py
  src/GafferDispatch/Dispatcher.cpp
  src/GafferDispatchModule/DispatcherBinding.cpp
Labels: pr-majorVersion

#2578 Async ImageView
  include/Gaffer/Action.h
  include/Gaffer/BackgroundTask.h
  include/Gaffer/ScriptNode.h
  include/GafferImageUI/ImageGadget.h
  python/GafferImageUI/ImageViewUI.py
  python/GafferImageUITest/ImageGadgetTest.py
  python/GafferTest/BackgroundTaskTest.py
  python/GafferUI/BackgroundMethod.py
  python/GafferUI/__init__.py
  python/GafferUITest/BackgroundMethodTest.py
  python/GafferUITest/__init__.py
  src/Gaffer/Action.cpp
  src/Gaffer/BackgroundTask.cpp
  src/Gaffer/Metadata.cpp
  src/Gaffer/ScriptNode.cpp
  src/GafferImageUI/ImageGadget.cpp
  src/GafferImageUI/ImageView.cpp
  src/GafferModule/ParallelAlgoBinding.cpp
  src/GafferModule/ScriptNodeBinding.cpp
Labels: pr-majorVersion
