Repository GafferHQ/gaffer, pull requests merged in 2018-02, with the labels that each got.

#2435 Avoid deprecated SearchPath methods
  python/GafferCortexTest/OpMatcherTest.py
  python/GafferCortexUI/ParameterPresets.py
  python/GafferUI/DocumentationAlgo.py
  python/GafferUI/Image.py
  src/GafferUI/Pointer.cpp
  startup/GafferScene/alembic.py
  startup/GafferScene/usd.py
  startup/gui/menus.py
Labels: pr-externalDependency

#2453 Wrapper : Initialise CORTEX_STARTUP_PATHS
  bin/gaffer
Labels: pr-externalDependency

#2468 ScriptNode : Save "current frame" with script
  apps/execute/execute-1.py
  apps/stats/stats-1.py
  include/Gaffer/ScriptNode.h
  python/GafferDispatchTest/ExecuteApplicationTest.py
  python/GafferTest/ScriptNodeTest.py
  python/GafferUI/ScriptNodeUI.py
  python/GafferUITest/PlaybackTest.py
  src/Gaffer/ScriptNode.cpp
Labels: pr-majorVersion

#2447 Backports for 0.3X_experimental_ai5
  config/ie/options
  include/Gaffer/Expression.h
  include/Gaffer/ScriptNode.h
  python/GafferArnoldTest/ArnoldRenderTest.py
  python/GafferArnoldUI/ArnoldOptionsUI.py
  python/GafferImageTest/CropTest.py
  python/GafferImageTest/ImageWriterTest.py
  python/GafferImageTest/images/defaultNegativeDisplayWindow.exr
  python/GafferImageUI/CatalogueUI.py
  python/GafferOSLUI/OSLShaderUI.py
  python/GafferSceneTest/ShaderAssignmentTest.py
  python/GafferSceneUI/FilterPlugValueWidget.py
  python/GafferSceneUI/LightTweaksUI.py
  python/GafferSceneUI/SceneInspector.py
  python/GafferSceneUI/SetUI.py
  python/GafferTest/BoxInTest.py
  python/GafferTest/ExpressionTest.py
  python/GafferTest/GraphComponentTest.py
  python/GafferTest/PlugAlgoTest.py
  python/GafferTest/ScriptNodeTest.py
  python/GafferTest/SubGraphTest.py
  python/GafferTractor/TractorDispatcher.py
  python/GafferTractorTest/TractorDispatcherTest.py
  python/GafferUI/ColorSwatchPlugValueWidget.py
  python/GafferUI/CompoundDataPlugValueWidget.py
  python/GafferUI/EditMenu.py
  python/GafferUI/FileMenu.py
  python/GafferUI/Menu.py
  python/GafferUI/MessageWidget.py
  python/GafferUI/NodeGraph.py
  python/GafferUI/NodeSetEditor.py
  python/GafferUI/PlugLayout.py
  python/GafferUI/ScriptNodeUI.py
  python/GafferUI/TabbedContainer.py
  python/GafferUI/_StyleSheet.py
  python/GafferUITest/PlaybackTest.py
  shaders/Pattern/FloatSpline.osl
  src/Gaffer/BoxIO.cpp
  src/Gaffer/Expression.cpp
  src/Gaffer/GraphComponent.cpp
  src/Gaffer/MonitorAlgo.cpp
  src/Gaffer/PlugAlgo.cpp
  src/Gaffer/ScriptNode.cpp
  src/Gaffer/SubGraph.cpp
  src/GafferArnold/ArnoldOptions.cpp
  src/GafferArnold/IECoreArnoldPreview/Renderer.cpp
  src/GafferBindings/CompoundNumericPlugBinding.cpp
  src/GafferBindings/ExpressionBinding.cpp
  src/GafferBindings/GraphComponentBinding.cpp
  src/GafferBindings/ScriptNodeBinding.cpp
  src/GafferBindings/Serialisation.cpp
  src/GafferImage/Catalogue.cpp
  src/GafferImage/Crop.cpp
  src/GafferImage/ImageWriter.cpp
  src/GafferImage/Text.cpp
  src/GafferScene/Preview/RendererAlgo.cpp
  src/GafferScene/ShaderPlug.cpp
  startup/gui/nodeGraph.py
Labels: pr-backport
