Repository GafferHQ/gaffer, pull requests merged in 2019-06, with the labels that each got.

#3141 Docs : Add "Python Scripting API" section and "The Python Editor" article
  doc/source/WorkingWithThePythonScriptingAPI/ThePythonEditor/.gitignore
  doc/source/WorkingWithThePythonScriptingAPI/ThePythonEditor/generate.sh
  doc/source/WorkingWithThePythonScriptingAPI/ThePythonEditor/images/taskAccessingElementsPythonEditor.gif
  doc/source/WorkingWithThePythonScriptingAPI/ThePythonEditor/index.md
  doc/source/WorkingWithThePythonScriptingAPI/ThePythonEditor/screengrab.py
  doc/source/WorkingWithThePythonScriptingAPI/index.md
  doc/source/index.md
Labels: component-docs

#3206 GafferUI : Backport compatibility patch to allow >0.54 layouts to load
  startup/GafferUI/layoutCompatibility.py
Labels: pr-backport

#3205 0.53.6.2 Backport
  Changes
  SConstruct
  include/GafferScene/Attributes.h
  python/GafferSceneTest/CustomAttributesTest.py
  python/GafferSceneUI/AttributesUI.py
  python/GafferSceneUI/CustomAttributesUI.py
  python/GafferUI/MultiLineTextWidget.py
  python/GafferUI/SplineWidget.py
  src/GafferArnold/ArnoldLight.cpp
  src/GafferScene/Attributes.cpp
  src/GafferSceneUI/StandardLightVisualiser.cpp
Labels: pr-backport

#3211 CompoundEditor : Add tab close buttons
  python/GafferUI/CompoundEditor.py
  python/GafferUI/_StyleSheet.py
  resources/graphics.svg
Labels: pr-revision

#3220 VectorTypedParameterHandler : Added support for Color3fVectorParameter
  python/GafferCortexUI/CompoundVectorParameterValueWidget.py
  src/GafferCortex/VectorTypedParameterHandler.cpp
Labels: pr-revision
