Repository GafferHQ/gaffer, pull requests merged in 2019-05, with the labels that each got.

#3169 Docs : Sphinx 1.8.0 compatibility
  doc/.gitignore
  doc/source/GettingStarted/ConfiguringGafferForThirdPartyTools/index.md
  doc/source/ReleaseNotes/generate.py
  python/GafferUI/DocumentationAlgo.py
Labels: component-docs

#3165 Docs : Cleanup pass
  .github/ISSUE_TEMPLATE/bug_report.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  PULL_REQUEST_TEMPLATE.md
  README.md
  doc/source/GettingStarted/ConfiguringGafferForThirdPartyTools/index.md
  doc/source/GettingStarted/InstallingGaffer/index.md
  doc/source/GettingStarted/LaunchingGafferFirstTime/index.md
  doc/source/GettingStarted/SettingUpGafferCommand/index.md
  doc/source/GettingStarted/index.md
  doc/source/Interface/ControlsAndShortcuts/index.md
  doc/source/Reference/ScriptingReference/Metadata/index.md
  doc/source/ScriptPerformance/index.md
  doc/source/Tutorials/BeginnerTutorial/index.md
  doc/source/Tutorials/Scripting/CreatingConfigurationFiles1/index.md
  doc/source/Tutorials/Scripting/CreatingConfigurationFiles2/index.md
  doc/source/Tutorials/Scripting/CreatingConfigurationFiles3/index.md
  doc/source/Tutorials/Scripting/GettingStarted/index.md
  doc/source/WorkingWithImages/AnatomyOfAnImage/index.md
  doc/source/WorkingWithScenes/AnatomyOfACamera/index.md
  doc/source/WorkingWithScenes/AnatomyOfAScene/index.md
  doc/source/WorkingWithScenes/Camera/index.md
  doc/source/WorkingWithScenes/LightLinking/index.md
  doc/source/WorkingWithTheNodeGraph/Box/index.md
  doc/source/WorkingWithTheNodeGraph/Box/screengrab.py
  doc/source/WorkingWithTheNodeGraph/Box/scripts/illustrationBoxReferences.gfr
  doc/source/WorkingWithTheNodeGraph/PerformanceBestPractices/.gitignore
  doc/source/WorkingWithTheNodeGraph/PerformanceBestPractices/index.md
  doc/source/WorkingWithTheNodeGraph/PerformanceBestPractices/screengrab.py
  doc/source/WorkingWithTheNodeGraph/PerformanceBestPractices/scripts/groupFirst.gfr
  doc/source/WorkingWithTheNodeGraph/PerformanceBestPractices/scripts/groupSecond.gfr
  doc/source/WorkingWithTheNodeGraph/UsingThePerformanceMonitor/.gitignore
  doc/source/WorkingWithTheNodeGraph/UsingThePerformanceMonitor/index.md
  doc/source/WorkingWithTheNodeGraph/UsingThePerformanceMonitor/screengrab.py
  doc/source/WorkingWithTheNodeGraph/index.md
  doc/source/index.md
Labels: component-docs

#3170 IECoreArnoldPreview : Remove unused lambda captures
  src/GafferArnold/IECoreArnoldPreview/Renderer.cpp
Labels: component-arnold, platform-osx, priority-high

#3172 Wildcard support for set names in set expressions
  python/GafferSceneTest/SetAlgoTest.py
  src/GafferScene/SetAlgo.cpp
Labels: docs-updateRequired
